version: '3.4'

services:

  encuestadb:
    build: mysql/
    image: andretr/encuestadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=encuesta
      - MYSQL_USER=app
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_HOST=%
    volumes: 
      - my-data:/var/lib/mysql/
    ports:
      - "3310:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my_network

  encuesta_monolito:
    build: backend/
    image: andretr/encuesta-backend:latest
    environment:
      - userPoolId=us-east-1_nTNZYp2XM
      - host=encuestadb
      - port=3306
      - database=encuesta
      - username=root
      - password=12345678
      - clientId=4liqf08q9atrnnf2dtiiqnl8uc
      - AWS_ACCESS_KEY_ID=XXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXX
    depends_on:
      - encuestadb
    ports:
      - "80:8080"
    restart: on-failure
    entrypoint: dockerize -wait tcp://encuestadb:3306 -timeout 10m java -jar /workspace/app.jar
    networks:
      - my_network

volumes:
  my-data:

networks:
  my_network: