version: '3.4'

####### REVISEN LAS FUENTES DEL MONOLITO PARA QUE VEAN DONDE SE CAMBIARON ALGUNOS VALORES ############

services:

  mysql_server:
    build: encuesta-mysql/
    image: encuestadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=encuesta
      - MYSQL_USER=app
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_HOST=%
    volumes: 
      - my-data:/var/lib/mysql/
    ports:
      - "3310:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

  monolito:
    build: encuesta-monolito/
    image: encuesta:latest
    environment: 
      - userPoolId=XXXXX
      - host=mysql_server
      - port=3306
      - database=encuesta
      - username=root
      - password=12345678
      - clientId=XXXXX
      - topico.aws.sns=XXXXX
      - AWS_ACCESS_KEY_ID=XXXX
      - AWS_SECRET_ACCESS_KEY=XXXX
    depends_on: 
      - mysql_server
    ports:
      - "80:8080"
    restart: on-failure
    entrypoint: dockerize -wait tcp://mysql_server:3306 -timeout 10m java -jar /workspace/app.jar
    networks:
      - backend

volumes:
  my-data:

networks:
  backend: 